services:
  pgbackup-prod:
    image: pgbackup/prod
    volumes:
    - ./backup:/backup

    env_file:
      - .env.production

  pgbackup-dev:
    image: pgbackup/prod
    volumes:
    - ./backup:/backup

    env_file:
      - .env.development